/// <reference types="next" />
/// <reference types="next/image-types/global" />

// NOTE: this file is normally auto-generated by `next dev` / `next build`.
// It's committed here as a placeholder so the project type-checks before
// the first build; Next.js will overwrite it on first run.
